### ISSUE TITLE
on website misspellings

### ISSUE THREAD

**Issue by voronoipotato** [tantaman/LargeLocalStorage#1]
LargeLocalStorage (or LLS) gives you a large capacity (up to several gig with permission from the user) key-value store in the browser.

For storage, LLS uses the FilesystemAPI when running in Chrome ~~Crome~~ and Opera, IndexedDB ~~InexedDB~~ in Firefox and IE and WebSQL in Safari.

**Comment by tantaman** [comment]
Thanks for pointing this out.

**Comment by voronoipotato** [comment]
No problem! :)
